export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'

export const CHANGE_LOOP_TYPE = 'player/CHANGE_LOOP_TYPE'

export const CHANGE_SONG_LIST = 'player/CHANGE_SONG_LIST'

export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'
